### ISSUE TITLE
Unrecognized body mode: undefined

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/postman-to-k6#18]
Trying to convert a Postman collection for the Load Impact API (find Postman collection in [this gist](https://gist.github.com/robingustafsson/23efce6e18d9a89b1bf38abeeddb46b1)) I get this:

```shell
Unrecognized body mode: undefined
Error: Unrecognized body mode: undefined
    at data (/<path-to>/postman-to-k6/lib/generate/Request.js:61:13)
    at Request (/<path-to>/postman-to-k6/lib/generate/Request.js:30:3)
    at Item (/<path-to>/postman-to-k6/lib/generate/Item.js:10:3)
    at ListMember (/<path-to>/postman-to-k6/lib/generate/ListMember.js:12:5)
    at module.exports.args (/<path-to>/postman-to-k6/lib/generate/ListMember.js:1:40)
    at ItemGroup (/<path-to>/postman-to-k6/lib/generate/ItemGroup.js:15:5)
    at ListMember (/<path-to>/postman-to-k6/lib/generate/ListMember.js:10:5)
    at module.exports.args (/<path-to>/postman-to-k6/lib/generate/ListMember.js:1:40)
    at Collection (/<path-to>/postman-to-k6/lib/generate/Collection.js:19:5)
    at convertObject (/<path-to>/postman-to-k6/lib/convert/object.js:40:3)
```

@bookmoons Could you have a look at this?

**Comment by bookmoons** [comment]
A few of these requests have a body section with no properties. Seems like it's an alternate encoding for no body. Submitted a patch to add support for it.
