### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by stormit-vn** [loadimpact/postman-to-k6#6]
I am getting this error when trying to convert a v2 postman collection with nested folder

TypeError: Cannot read property 'body' of undefined
    at convertToK6Request (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/lib/postman/k6-generator.js:115:21)
    at PostmanItemGroup.<anonymous> (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/lib/postman/k6-generator.js:50:23)
    at /Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:2874:23
    at /Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:3346:13)
    at PostmanPropertyList.each (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/postman-collection/lib/collection/property-list.js:199:11)
    at PostmanCollection.<anonymous> (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/lib/postman/k6-generator.js:48:22)
    at /Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:2874:23
    at /Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/Users/hoangle/.nvm/versions/node/v6.10.2/lib/node_modules/postman-to-k6/node_modules/lodash/index.js:3346:13)

Any hint to fix this issue?

**Comment by ppcano** [comment]
@stormit-vn Thanks for reporting.  I have published a new release (0.0.3) with the fix.

Let us know if it works now to close the issue.
