### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by davidhopkins** [loadimpact/postman-to-k6#65]
Installed the tool and ran it against the echo example but when it comes to executing that I get a JS error that seems quite fundamental

```
❯ npm install -g postman-to-k6
/usr/local/bin/postman-to-k6 -> /usr/local/lib/node_modules/postman-to-k6/bin/postman-to-k6.js

> postman-to-k6@1.1.0 postinstall /usr/local/lib/node_modules/postman-to-k6
> node scripts/bundle.js

+ postman-to-k6@1.1.0
updated 1 package in 3.456s

❯ postman-to-k6 echo.json -o k6-rg.js
❯ k6 run k6-rg.js

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     script: k6-rg.js
     output: -

  scenarios: (100.00%) 1 executors, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

ERRO[0005] TypeError: Cannot read property 'indexOf' of undefined
running at executePostrequest (file:///Users/david/projects/k6.x/libs/shim/core.js:1196:203(90))
default at executeRequest (file:///Users/david/projects/k6.x/libs/shim/core.js:985:25(128))
        at executeRequest (file:///Users/david/projects/k6.x/libs/shim/core.js:968:5(57))
        at file:///Users/david/projects/k6.x/libs/shim/core.js:307:46(35)
        at file:///Users/david/projects/k6.x/k6-rg.js:16:21(28)
        at native
        at file:///Users/david/projects/k6.x/k6-rg.js:15:17(5)  executor=per-vu-iterations scenario=default

running (00m00.6s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m00.5s/10m0s  1/1 iters, 1 per VU


    █ Auth: Digest

    data_received..............: 5.7 kB 10 kB/s
    data_sent..................: 942 B  1.7 kB/s
    group_duration.............: avg=530.41ms min=530.41ms med=530.41ms max=530.41ms p(90)=530.41ms p(95)=530.41ms
    http_req_blocked...........: avg=435.83ms min=435.83ms med=435.83ms max=435.83ms p(90)=435.83ms p(95)=435.83ms
    http_req_connecting........: avg=95.78ms  min=95.78ms  med=95.78ms  max=95.78ms  p(90)=95.78ms  p(95)=95.78ms 
    http_req_duration..........: avg=93.75ms  min=93.75ms  med=93.75ms  max=93.75ms  p(90)=93.75ms  p(95)=93.75ms 
    http_req_receiving.........: avg=112µs    min=112µs    med=112µs    max=112µs    p(90)=112µs    p(95)=112µs   
    http_req_sending...........: avg=203µs    min=203µs    med=203µs    max=203µs    p(90)=203µs    p(95)=203µs   
    http_req_tls_handshaking...: avg=302.85ms min=302.85ms med=302.85ms max=302.85ms p(90)=302.85ms p(95)=302.85ms
    http_req_waiting...........: avg=93.43ms  min=93.43ms  med=93.43ms  max=93.43ms  p(90)=93.43ms  p(95)=93.43ms 
    http_reqs..................: 1      1.795026/s
    iteration_duration.........: avg=530.45ms min=530.45ms med=530.45ms max=530.45ms p(90)=530.45ms p(95)=530.45ms
    iterations.................: 1      1.795026/s
```
I tried installing the tool using the non global as well but it didn't seem to make a difference. Here's the versions I'm using:
```
❯ k6 version
k6 v0.27.1 (dev build, go1.14.5, darwin/amd64)
❯ postman-to-k6 -V
1.1.0
```

**Comment by simskij** [comment]
Thank you for the report! This will be resolved by a4534ed
